### ISSUE TITLE
release 0.4.x

### ISSUE THREAD

**Issue by harlantwood** [ipfs/npm-go-ipfs#10]

**Comment by jbenet** [comment]
wait, why isn't this happening!? it's part of the go-ipfs release checklist https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md

cc @whyrusleeping @Kubuxu ??

**Comment by whyrusleeping** [comment]
It appears this doesnt happen because this package relies on gobuilder

**Comment by whyrusleeping** [comment]
@diasdavid mentioned there was a different npm package for getting the go-ipfs daemon in javascript.

**Comment by diasdavid** [comment]
[js-ipfsd-ctl]((https://github.com/ipfs/js-ipfsd-ctl/blob/master/package.json#L46)) relies on [`go-ipfs-dep`](https://github.com/diasdavid/go-ipfs-dep) now, it is a simpler version of npm-go-ipfs that works with `dist.ipfs.io` instead of go-builder.

For now it is just 0.4.1, as we can't update to 0.4.2 due to a bug in 0.4.2.

@jgantunes is doing a really awesome work of upgrading js-ipfsd-ctl to use binwrapper, that will solve the Arch problem https://github.com/ipfs/js-ipfsd-ctl/pull/89

I'll go ahead an update this module description to point to go-ipfs-dep.

**Comment by harlantwood** [comment]
@diasdavid if I read this correctly, I understand that:

1. this module ( https://github.com/ipfs/npm-go-ipfs ) is deprecated
1. https://github.com/diasdavid/go-ipfs-dep is the replacement

Correct?

**Comment by paul90** [comment]
Looks as if this is still not resolved. 

If this module is deprecated then it needs a deprecate message adding in npm to point to the correct place. Also the readme there needs updating to install the correct npm package, and not this one.

**Comment by jbenet** [comment]
guys, come on! people depend on this module-- including me. it wasted 20min of my time to realize that this was go-ipfs 0.3x being installed...

**Comment by jbenet** [comment]
this module should not be deprecated-- why do people think it is? the goal of this module is to enable this:

```sh
npm install go-ipfs
node_modules/.bin/ipfs version
```
and this
```sh
npm install -g go-ipfs
ipfs version
```

it should be using dist.ipfs.io

**Comment by jbenet** [comment]
I'm on this, fixing it.

**Comment by jbenet** [comment]
Okay, fixed. I published:

```
0.4.0 as 0.4.0-hacky2
0.4.1 as 0.4.1-hacky2
0.4.2 as 0.4.2-npmfix2
0.4.3 as 0.4.3-npmfix1
0.4.4 as 0.4.4
```

sorry for the silly version suffixes.

---
```
> npm view go-ipfs versions

[ '0.2.3',
  '0.2.4',
  '0.2.5',
  '0.2.6',
  '0.2.7',
  '0.2.8',
  '0.2.9',
  '0.2.10',
  '0.2.11',
  '0.3.0',
  '0.3.2-2',
  '0.3.2',
  '0.3.4-2',
  '0.3.4-3',
  '0.3.4',
  '0.3.5-2',
  '0.3.5',
  '0.3.6-1',
  '0.3.6-2',
  '0.3.6',
  '0.3.7-2',
  '0.3.7-3',
  '0.3.7-fix',
  '0.3.7',
  '0.3.8-1',
  '0.3.8',
  '0.3.9',
  '0.3.10',
  '0.3.11',
  '0.4.0-hacky2',
  '0.4.1-hacky2',
  '0.4.2-npmfix2',
  '0.4.3-npmfix1',
  '0.4.4' ]
```

**Comment by harlantwood** [comment]
Awesome, thanks.  For the record, this is exactly what I want too: an executable that can be run from the shell, but managed via NPM.

**Comment by harlantwood** [comment]
> wait, why isn't this happening!? it's part of the go-ipfs release checklist https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md

Not sure where to properly file this, but maybe there could be a check on CI that would fail if all of the steps for a given release were not completed (at least those, like this one, that are easy to check automatically).
