### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by izqui** [ipfs/npm-go-ipfs#17]
Seems like the [update to 0.4.18](https://github.com/ipfs/npm-go-ipfs/commit/c94e39250a2b16b4ac03bdd5cb7f9b984441f645) has broken the build. I think it is related to that new `bin/ipfs` file that has a reference to a local file.

We are pinning to version 0.4.17 for the time being. You can check user reports and logs in the issue in our repo: https://github.com/aragon/aragon-cli/issues/257

**Comment by diasdavid** [comment]
Thank you @izqui, this was my mistake when releasing the last one. Released a new version without the binary included. Could you test again please?

**Comment by diasdavid** [comment]
@izqui closing, let me know if need to reopen.
