### ISSUE TITLE
go-ipfs version is out of date in NPM

### ISSUE THREAD

**Issue by daviddias** [ipfs/npm-go-ipfs#21]
Hi @olizilla! I'm wondering if there was any blocker to not get go-ipfs to auto publish just like https://www.npmjs.com/package/go-ipfs-dep. If not, can you do the same magic?

**Comment by daviddias** [comment]
I've just manually published it. Still, it would be good to automate.

**Comment by olizilla** [comment]
Yep. For context, what's the story behind having two modules that do almost the same thing?

**Comment by daviddias** [comment]
One is to be used as a dependency and the other is to have a easy path for Node.js people to install go-ipfs globally (this was an observation made late 2014/early 2015 that we carried onwards).

**Comment by achingbrain** [comment]
Github updated their actions API which broke auto publishing but it's fixed by #29.  Also this module is now a drop-in replacement for `go-ipfs-dep` and no longer depends on it so that one can be retired.
