### ISSUE TITLE
Binary Hosting Causes Intermittent Failure

### ISSUE THREAD

**Issue by OR13** [ipfs/npm-go-ipfs#22]
Try to install go-ipfs:

```
npm i go-ipfs --save-dev
```

Wait until you see:

```
...
Downloading https://dist.ipfs.io/go-ipfs/v0.4.21/go-ipfs_v0.4.21_darwin-amd64.tar.gz
```

This will never finish...

This will cause any project that depends on `go-ipfs` npm module to become not installable.

Solution:

Host go-ipfs binaries on S3 / Blob Storage / Whatever, and fall back to that if IPFS network is down, or requests for IPFS binaries from IPFS take longer than TIMEOUT seconds.

**Comment by OR13** [comment]
Workaround, try various other versions, maybe one will succeed:

```
 npm i go-ipfs@0.4.17 --save-dev
```

**Comment by OR13** [comment]
Now failing to install because of:

```
FetchError: request to https://dist.ipfs.io/go-ipfs/versions failed, reason: unable to verify the first certificate
Download failed!
```

**Comment by Stebalien** [comment]
> Workaround, try various other versions, maybe one will succeed:

Trying other versions should be the same as re-trying the same version.

> FetchError: request to https://dist.ipfs.io/go-ipfs/versions failed, reason: unable to verify the first certificate

Where are you (approximately)? None of the gateway/IPFS issues should be causing certificate errors.

**Comment by OR13** [comment]
Austin Texas.

I was able to download by turning off TLS : / (nobody do this please).

```
NODE_TLS_REJECT_UNAUTHORIZED=0 npm i
```

**Comment by Stebalien** [comment]
Reporting to our infra.

**Comment by achingbrain** [comment]
This was an intermittent infrastructure issue which has been resolved, please reopen if you are still having problems with this module.
