### ISSUE TITLE
Last three updates to this module did not actually change the version of go-ipfs installed

### ISSUE THREAD

**Issue by andrew** [ipfs/npm-go-ipfs#25]
This module has been borked for a while now, looks like the update.js script stopped working after 0.4.22 as running now results in no changes, and running `./publish.sh 0.5.1`, as @Stebalien has been doing, only changes the version of this module, not the version of `go-ipfs-dep` which does the actually installing.

See commits [v0.4.23](https://github.com/ipfs-shipyard/npm-go-ipfs/commit/b1ec751967c49d941486fe72ffccff627dcdaebf), [v0.5.0](https://github.com/ipfs-shipyard/npm-go-ipfs/commit/3d4b9f6cab69ed1c711219bb89331ddcdb9a396e) and [v0.5.1](https://github.com/ipfs-shipyard/npm-go-ipfs/commit/b8d196714a9d58ded813e1af33786cf2155747e9)

If you try to install the latest (0.5.1) version of this module via the cli, it actually installs go-ipfs 0.4.22.

``` bash
$ npm install -g go-ipfs --force
npm WARN using --force I sure hope you know what you are doing.
/usr/local/bin/ipfs -> /usr/local/lib/node_modules/go-ipfs/bin/ipfs

> go-ipfs-dep@0.4.22 install /usr/local/lib/node_modules/go-ipfs/node_modules/go-ipfs-dep
> node src/bin.js

Downloading https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_darwin-amd64.tar.gz
Downloaded go-ipfs_v0.4.22_darwin-amd64.tar.gz
Installed go-go-ipfs v0.4.22 darwin-amd64 to /usr/local/lib/node_modules/go-ipfs/node_modules/go-ipfs-dep/go-ipfs/

> go-ipfs@0.5.1 install /usr/local/lib/node_modules/go-ipfs
> node link-ipfs.js

version mismatch: expected 0.5.1 got 0.4.22
+ go-ipfs@0.5.1
added 63 packages from 41 contributors in 15.255s
```

The [npm package](https://www.npmjs.com/package/go-ipfs) is only getting ~250 installs a week (a 10th of the go-ipfs-dep installs) but is depended upon by some other modules: [@dapp-stack/web](https://www.npmjs.com/package/@dapp-stack/web), [@rxdi/deploy](https://www.npmjs.com/package/@rxdi/deploy), [@dapp-stack/ipfs](https://www.npmjs.com/package/@dapp-stack/ipfs)
and [@67p/aragon-cli](https://www.npmjs.com/package/@67p/aragon-cli)

**Comment by achingbrain** [comment]
This should be fixed now, please try again.

**Comment by andrew** [comment]
Yep working as expected now, previous versions are still borked but I guess there's not much we can do about those since we can't replace the versions published to npmjs.org
