### ISSUE TITLE
Install fails on apple m1 machines

### ISSUE THREAD

**Issue by JonasKruckenberg** [ipfs/npm-go-ipfs#40]
Greetings fellow dwebians!
When installing `go-ipfs` on apple m1 machines the Installation fails with the error `No binary available for arch 'undefined'`. This is an upstream error that I already fixed through [node-go-platform#1](https://github.com/jbenet/node-go-platform/pull/1).
Maybe when you guys can do a bit of lobbying to get this PR through it would be much appreciated!

**Comment by vigasdeep** [comment]
@achingbrain hey! do you know when this merge will be available at https://www.npmjs.com/package/go-ipfs ?

It currently ships v0.11.0 and M1 machines aren't able to use it.
