### ISSUE TITLE
dist.ipfs.io is dead?

### ISSUE THREAD

**Issue by bluelovers** [ipfs/npm-go-ipfs#42]
![image](https://user-images.githubusercontent.com/167966/130275947-5226d4c0-b1d4-49c5-a479-43a5b9c8c07c.png)

![image](https://user-images.githubusercontent.com/167966/130276000-6419e5f6-5d60-426e-9882-b7a0b470792a.png)

**Comment by Stebalien** [comment]
See https://ipfsgateway.statuspage.io/. It's back up now.
