### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by GoogilyBoogily** [ipfs/npm-go-ipfs#6]
Doesn't work unless "case "windows":" is inserted at line 60.

**Comment by dignifiedquire** [comment]
Thanks for the report

**Comment by zoernert** [comment]
Still exists:
Error: no binary available for os:windows

**Comment by jbenet** [comment]
This should work now, with go-ipfs builds that have windows binaries in https://dist.ipfs.io
